{% set name = "pyUSID" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 545a2e23d1dd9448d812eebab7f5dec14645881318e3a012a84d3d8e92618a33

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.10
    - dask >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - psutil
    - six
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython >=6.0
    - pillow
    - sidpy >=0.0.1

test:
  imports:
    - pyUSID

about:
  home: https://github.com/pycroscopy/pyUSID
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Framework for storing, visualizing, and processing Universal Spectroscopic and Imaging Data (USID)
  doc_url: https://pycroscopy.github.io/pyUSID/
  dev_url: https://github.com/pycroscopy/pyUSID

extra:
  recipe-maintainers:
    - ssomnath
    - compphyschris
    - carlodri
