appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cl76nSgZcQk2tdMB0KnGMoITfTsyANasNkuOzOI5TOAyIV5G6kru9pn3bq8rlyES4gvT+NxPoQWY53Oj0tk/pOLcmWAYt0kYuzh+Tsn7FLz4lwssxbsDWebZ/eYiOr7S5IPzyqFdjO9INFpdUDxv2OPF9OI4E1w6GkEjhJ1hMMJluFSRlVrILUCoYw+6lw2tRaO4HChJlGh1NryrkPIg1biwcAxaQJOxAnYVOPVWWpJF9NI0ahcXy13TV8HIGgFRc+Qo+DwEv+DTCoFpvBsXrzqtVRvdiHXvM+8QpN45OMO4y/OpBjnjvzZxl1GR71HN85SBYGDtCuI4vVUXlPZ6G1ItekidYiW5HabVYFb9+h58yiP8/TAsQwMS2ZXOhq93625t+Aq2jtCUnSQuCTUXKi6aQfjdWWc+pevhFy4DyGzrhNuch7sy38ouDK3dcx6eb2PEqTL6/PkqGKDT7PJzz+9/TwKjqpyRuBmzp38I57PBma7H3dU26ahrIiN5UnaEOmHr4iJ5lAc+ra9FbauCJtzKo6Pc50TNR0Y9lhNB5VDxFDpzdRvkOoVUEUZlSQ72k2UL2WCn5qTJLnPXBsc+xe/yg+eB5GW47oMD5RiucIrLtz6J9vg+Q+B8tY1bD8sATnCxOi9oHqZZOftc2NvR4jCKj8J2mYO/bL+JxX8GPn4=}
provider:
  win: azure
conda_forge_output_validation: true
